# Generated by Django 2.2.7 on 2020-09-16 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chall_0', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
