# Generated by Django 2.2.7 on 2020-10-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('spyder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='flag',
            field=models.CharField(default='NSS{SpiderCrawling}', max_length=12),
        ),
    ]
