# Generated by Django 2.2.7 on 2020-10-08 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userName',
        ),
    ]
