# Generated by Django 2.2.7 on 2020-10-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recruit', '0004_auto_20201014_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='signUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.EmailField(max_length=254)),
                ('userPassword', models.CharField(max_length=512)),
                ('userQQ', models.IntegerField()),
                ('userFlagCount', models.IntegerField(default=0)),
                ('solved', models.CharField(default='{}', max_length=512, null=True)),
                ('sid', models.IntegerField()),
                ('name', models.CharField(max_length=16)),
            ],
        ),
    ]
