# Generated by Django 2.2.7 on 2020-10-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chall', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(default='NSS{fake_flag}', max_length=64)),
                ('chall', models.IntegerField()),
            ],
        ),
    ]
